CREATE TABLE "public"."customers_cube)" (
"user_id" text DEFAULT NULL,
"first_visit_date" date DEFAULT NULL,
"email_address" text DEFAULT NULL,
"country" text DEFAULT NULL,
"visit_unique_id" text DEFAULT NULL,
"visit_counter" int2 DEFAULT NULL,
"stage_in_purchase_funnel_reached" text DEFAULT NULL,
"mkt_source" text DEFAULT NULL,
"mkt_medium" text DEFAULT NULL,
"mkt_campaign" text DEFAULT NULL,
"mkt_term" text DEFAULT NULL,
"mkt_content" text DEFAULT NULL,
"mkt_paid" bool DEFAULT NULL,
"mkt_rank" int2 DEFAULT NULL,
"mkt_page" int2 DEFAULT NULL,
"dvce_ismobile" bool DEFAULT NULL,
"dvce_type" text DEFAULT NULL,
"dvce_screenwidth" int2 DEFAULT NULL,
"dvce_screenheight" int2 DEFAULT NULL,
"br_name" text DEFAULT NULL,
"br_family" text DEFAULT NULL,
"br_version" text DEFAULT NULL,
"br_type" text DEFAULT NULL,
"br_renderengine" text DEFAULT NULL,
"br_lang" text DEFAULT NULL,
"br_features_pdf" bool DEFAULT NULL,
"br_features_flash" bool DEFAULT NULL,
"br_featurse_java" bool DEFAULT NULL,
"br_features_director" bool DEFAULT NULL,
"br_features_quicktime" bool DEFAULT NULL,
"br_features_realplayer" bool DEFAULT NULL,
"br_featurse_windowsmedia" bool DEFAULT NULL,
"br_features_gears" bool DEFAULT NULL,
"br_features_silverlight" bool DEFAULT NULL,
"page_views" int4 DEFAULT NULL,
"unique_pages_per_visit" int4 DEFAULT NULL,
"actions" int4 DEFAULT NULL,
"product_pages_visited" int4 DEFAULT NULL,
"unique_product_pages_visited" int4 DEFAULT NULL,
"add_to_baskets" int4 DEFAULT NULL,
"value_of_goods_added_to_basket" int4 DEFAULT NULL,
"revenue" float4 DEFAULT NULL
)
WITH (OIDS=FALSE)
;

ALTER TABLE "public"."customers_cube)" OWNER TO "postgres";
